In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
import statistics
from math import sqrt
from scipy import stats

In [2]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def metrics_c(actual, pred):
  return {
    'Accuracy': accuracy_score(actual, pred),
    'Precision': precision_score(actual, pred),
    'Recall': recall_score(actual, pred),
    'F1-score': f1_score(actual, pred),
    'ROC_AUC': roc_auc_score(actual, pred)
  }
models_c = {}

In [3]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error, r2_score
from math import sqrt

def metrics_r(actual, pred):
  return {
    'MAE': mean_absolute_error(actual, pred),
    'MSE': mean_squared_error(actual, pred),
    'RMSE': sqrt(mean_squared_error(actual, pred)),
    'MAPE': mean_absolute_percentage_error(actual, pred),
    'R^2': r2_score(actual, pred)
  }
models_r = {}

In [4]:
data_classification = pd.read_csv('my_card_transdata.csv', sep=";")

In [5]:
data_classification.head(5)

Unnamed: 0  distance_from_home  distance_from_last_transaction  \
0           0           57.877857                        0.311140   
1           1           10.829943                        0.175592   
2           2            5.091079                        0.805153   
3           3            2.247564                        5.600044   
4           4           44.190936                        0.566486   

   ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                        1.945940             True       True   
1                        1.294219             True      False   
2                        0.427715             True      False   
3                        0.362663             True       True   
4                        2.222767             True       True   

   used_pin_number  online_order  fraud  
0            False         False  False  
1            False         False  False  
2            False          True  False  
3            False          True  False  
4            False          True  False

In [6]:
data_classification.drop(columns = ["Unnamed: 0"], inplace=True)

In [7]:
for i in data_classification:
    data_classification[i]=data_classification[i].astype('float64')

In [8]:
data_classification.head()

distance_from_home  distance_from_last_transaction  \
0           57.877857                        0.311140   
1           10.829943                        0.175592   
2            5.091079                        0.805153   
3            2.247564                        5.600044   
4           44.190936                        0.566486   

   ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                        1.945940              1.0        1.0   
1                        1.294219              1.0        0.0   
2                        0.427715              1.0        0.0   
3                        0.362663              1.0        1.0   
4                        2.222767              1.0        1.0   

   used_pin_number  online_order  fraud  
0              0.0           0.0    0.0  
1              0.0           0.0    0.0  
2              0.0           1.0    0.0  
3              0.0           1.0    0.0  
4              0.0           1.0    0.0

In [9]:
data_regression = pd.read_csv('my_diamonds.csv', sep=";")

In [10]:
data_regression.head()

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x     y  \
0           0   0.23    4      1        1   61.5   55.0    326  3.95  3.98   
1           1   0.21    5      1        2   59.8   61.0    326  3.89  3.84   
2           3   0.29    5      2        4   62.4   58.0    334  4.20  4.23   
3           4   0.31    1      3        1   63.3   58.0    335  4.34  4.35   
4           5   0.24    2      3        5   62.8   57.0    336  3.94  3.96   

      z  
0  2.43  
1  2.31  
2  2.63  
3  2.75  
4  2.48

In [11]:
data_regression.drop(columns = ["Unnamed: 0"], inplace=True)

data_regression.head()

carat  cut  color  clarity  depth  table  price     x     y     z
0   0.23    4      1        1   61.5   55.0    326  3.95  3.98  2.43
1   0.21    5      1        2   59.8   61.0    326  3.89  3.84  2.31
2   0.29    5      2        4   62.4   58.0    334  4.20  4.23  2.63
3   0.31    1      3        1   63.3   58.0    335  4.34  4.35  2.75
4   0.24    2      3        5   62.8   57.0    336  3.94  3.96  2.48

In [12]:
y_regression = data_regression["price"]
X_regression = data_regression.drop(columns = ['price'])

y_classification = data_classification['fraud']
X_classification = data_classification.drop(columns = ['fraud'])

In [13]:
data_classification.loc[(data_classification['fraud'] == "True"), 'fraud'] = 1
data_classification.loc[(data_classification['fraud'] == "False"), 'fraud'] = 0
for i in data_classification:
    data_classification[i]=data_classification[i].astype('float64')


In [14]:
from sklearn.model_selection import train_test_split

X_regression_train, X_regression_test, y_regression_train, y_regression_test = train_test_split(X_regression, y_regression, test_size=0.2)
X_classification_train, X_classification_test, y_classification_train, y_classification_test = train_test_split(X_classification, y_classification, stratify=y_classification, test_size=0.2)

Импортируем метрики

In [15]:
# для оценки качества решения задачи регрессии
from sklearn.metrics import mean_squared_error, mean_absolute_error
# для оценки качества решения задачи классификации
from sklearn.metrics import confusion_matrix, classification_report

In [16]:
import tensorflow as tf
from tensorflow import keras

### Регрессия

Создаем полносвязную нейронную сеть для решения задачи регрессии

In [17]:
# создаем модель, как набор последовательных слоев
model_regression = tf.keras.Sequential(
    [
        # Dense - полносвязный слой (каждый нейрон следующего слоя связан со всеми нейронами предыдущего)
        tf.keras.layers.Dense(64, activation="relu", input_shape=(9,)),
        # на втором скрытом слое будет 32 нейрона
        tf.keras.layers.Dense(32, activation="linear"),
        # Dropout позволяет внести фактор случайности - при обучении часть нейронов будет отключаться
        # каждый нейрон, в данном случае, будет отключаться с вероятностью 0.1
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dropout(0.1),
        # на выходе один нейрон, функция активации не применяется
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)

In [18]:
# посмотрим, какая сеть у нас получилась
model_regression.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                640       
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 16)                528       
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 3265 (12.75 KB)
Trainable params: 3265 (12

In [19]:
# компилируем
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mse")

In [20]:
# обучаем, 10 эпох означает 10 проходов по обучающей выборке
model_regression.fit(X_regression_train, y_regression_train, epochs=50)

Epoch 1/50
1145/1145 [==============================] - 8s 5ms/step - loss: 3055759.5000
Epoch 2/50
1145/1145 [==============================] - 5s 5ms/step - loss: 1175864.2500
Epoch 3/50
1145/1145 [==============================] - 7s 6ms/step - loss: 1180113.0000
Epoch 4/50
1145/1145 [==============================] - 4s 3ms/step - loss: 1125760.6250
Epoch 5/50
1145/1145 [==============================] - 2s 2ms/step - loss: 1119516.1250
Epoch 6/50
1145/1145 [==============================] - 2s 2ms/step - loss: 1125331.7500
Epoch 7/50
1145/1145 [==============================] - 3s 3ms/step - loss: 1113121.8750
Epoch 8/50
1145/1145 [==============================] - 2s 2ms/step - loss: 1133019.2500
Epoch 9/50
1145/1145 [==============================] - 2s 2ms/step - loss: 1121297.1250
Epoch 10/50
1145/1145 [==============================] - 2s 2ms/step - loss: 1105969.7500
Epoch 11/50
1145/1145 [==============================] - 2s 2ms/step - loss: 1116510.7500
Epoch 12/50
1145/11

In [21]:
metrics_r(y_regression_test, model_regression.predict(X_regression_test))

287/287 [==============================] - 1s 1ms/step


{'MAE': 400.0740247608729,
 'MSE': 442461.70513518504,
 'RMSE': 665.1779499766849,
 'MAPE': 0.14169422090065048,
 'R^2': 0.9404789894777471}

### Бинарная классификация

In [22]:
model_classification = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(7,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

In [23]:
X_train_classifier = X_classification_train.astype('float64')
y_train_classifier = y_classification_train.astype('float64')

In [24]:
# в качестве функции активации используется бинарная  кроссэнтропия
model_classification.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse")
# verbose=None - не будет логов
model_classification.fit(X_classification_train, y_classification_train, epochs=25, verbose=None)

model_classification.predict(X_classification_test, verbose=None)[:5]

array([[7.2179138e-12],
       [1.3099837e-17],
       [3.6642844e-16],
       [1.4072362e-14],
       [2.3697468e-12]], dtype=float32)

In [25]:
yc_pred = np.around(model_classification.predict(X_classification_test, verbose=None))

print(classification_report(y_classification_test, yc_pred))
confusion_matrix(y_classification_test, yc_pred)

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     25101
         1.0       0.99      0.97      0.98      2392

    accuracy                           1.00     27493
   macro avg       0.99      0.99      0.99     27493
weighted avg       1.00      1.00      1.00     27493



array([[25070,    31],
       [   64,  2328]])

In [26]:
# Fix
w0 = 1 / y_train_classifier[y_train_classifier==0].shape[0]
w1 = 1 / y_train_classifier[y_train_classifier==1].shape[0]

In [27]:
model_classification_2 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(7,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 2 нейрона и softmax
        tf.keras.layers.Dense(2, activation="softmax"),
    ]
)

In [28]:
# в качестве функции активации используется категориальная кроссэнтропия
# используем разряженный (sparse) вариант, поскольку значения целевого признака не закодированы One-Hot кодированием
model_classification_2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="sparse_categorical_crossentropy")

In [29]:
model_classification_2.fit(X_train_classifier, y_train_classifier, epochs=25, verbose=None, class_weight={0: w0, 1: w1})
model_classification_2.predict(X_classification_test, verbose=None)[:5]

array([[9.9996775e-01, 3.2197524e-05],
       [9.0949762e-01, 9.0502322e-02],
       [9.9999839e-01, 1.6016329e-06],
       [9.9999839e-01, 1.5919918e-06],
       [9.9996883e-01, 3.1074698e-05]], dtype=float32)

In [30]:
# получим индексы максимального значения для каждого элемента (вложенный массив) с помощью numpy
yc_pred = [np.argmax(pred) for pred in model_classification_2.predict(X_classification_test, verbose=None)]

In [31]:
print(classification_report(y_classification_test, yc_pred))
confusion_matrix(y_classification_test, yc_pred)

              precision    recall  f1-score   support

         0.0       1.00      0.97      0.99     25101
         1.0       0.77      1.00      0.87      2392

    accuracy                           0.97     27493
   macro avg       0.89      0.98      0.93     27493
weighted avg       0.98      0.97      0.98     27493



array([[24402,   699],
       [    6,  2386]])

## 2 задание

In [32]:
import numpy as np

class MLP:
    def __init__(self, layer_sizes, activation_functions):
        self.num_layers = len(layer_sizes)
        self.layer_sizes = layer_sizes
        self.activation_functions = activation_functions
        self.weights = [np.random.randn(layer_sizes[i], layer_sizes[i-1]) for i in range(1, self.num_layers)]
        self.biases = [np.random.randn(layer_sizes[i], 1) for i in range(1, self.num_layers)]

    def _sigmoid(self, x):
        return 1.0 / (1.0 + np.exp(-x))

    def _sigmoid_derivative(self, x):
        return self._sigmoid(x) * (1 - self._sigmoid(x))

    def _tanh(self, x):
        return np.tanh(x)

    def _tanh_derivative(self, x):
        return 1 - np.tanh(x)**2

    def _relu(self, x):
        return np.maximum(0, x)

    def _relu_derivative(self, x):
        return np.where(x > 0, 1, 0)

    def _feed_forward(self, x):
        activations = [x]
        zs = []
        for i in range(self.num_layers - 1):
            weight = self.weights[i]
            bias = self.biases[i]
            activation_fn = self.activation_functions[i]
            z = np.dot(weight, activations[-1]) + bias
            zs.append(z)
            if activation_fn == 'sigmoid':
                a = self._sigmoid(z)
            elif activation_fn == 'tanh':
                a = self._tanh(z)
            elif activation_fn == 'relu':
                a = self._relu(z)
            activations.append(a)
        return activations, zs

    def _backpropagate(self, x, y):
        delta_weights = [np.zeros(weight.shape) for weight in self.weights]
        delta_biases = [np.zeros(bias.shape) for bias in self.biases]
        activations, zs = self._feed_forward(x)
        delta = (activations[-1] - y)  # derivative of the loss function
        for i in range(self.num_layers - 2, -1, -1):
            z = zs[i]
            activation_fn = self.activation_functions[i]
            if activation_fn == 'sigmoid':
                derivative = self._sigmoid_derivative(z)
            elif activation_fn == 'tanh':
                derivative = self._tanh_derivative(z)
            elif activation_fn == 'relu':
                derivative = self._relu_derivative(z)
            delta_weights[i] = np.dot(delta, activations[i].T)
            delta_biases[i] = delta
            delta = np.dot(self.weights[i].T, delta) * derivative
        return delta_weights, delta_biases

    def train(self, X_train, y_train, learning_rate, num_epochs):
        for epoch in range(num_epochs):
            for x, y in zip(X_train, y_train):
                x = np.array(x, ndmin=2).T
                y = np.array(y, ndmin=2).T
                delta_weights, delta_biases = self._backpropagate(x, y)
                self.weights = [weight - learning_rate * d_weight for weight, d_weight in zip(self.weights, delta_weights)]
                self.biases = [bias - learning_rate * d_bias for bias, d_bias in zip(self.biases, delta_biases)]

    def predict(self, X_test):
        predictions = []
        for x in X_test:
            x = np.array(x, ndmin=2).T
            activations, _ = self._feed_forward(x)
            predictions.append(activations[-1])
        return predictions

In [33]:
X_train_regression = np.asarray(X_regression_train, dtype=np.float64)
y_train_regression = np.asarray(y_regression_train, dtype=np.float64).reshape(-1, 1)
# Создание объекта MLP для регрессии
mlp_regression = MLP([9, 1, 1], ['sigmoid', 'sigmoid'])

# Обучаем модель
mlp_regression.train(X_train_regression, y_train_regression, learning_rate=0.05, num_epochs=10)

X_test_regression = np.asarray(X_regression_test, dtype=np.float64)
# Получаем предсказания модели
predictions_regression = mlp_regression.predict(X_test_regression)

<ipython-input-32-36c8a1712f5e>:12: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-x))


In [ ]:
y_test_regression = np.asarray(y_regression_train, dtype=np.float64).reshape(-1, 1)
from sklearn.metrics import r2_score
print(mean_absolute_error(y_test_regression, predictions_regression))
print(mean_squared_error(y_test_regression, predictions_regression))
print(r2_score(y_test_regression, predictions_regression))

In [36]:
X_train_classifier = np.asarray(X_train_classifier, dtype=np.float64)
y_train_classifier = np.asarray(y_train_classifier, dtype=np.float64).reshape(-1, 1)
mlp_classifier = MLP([7, 1, 1, 1], ['tanh', 'relu', 'sigmoid'])

mlp_classifier.train(X_train_classifier, y_train_classifier, learning_rate=0.05, num_epochs=10)

X_test_classifier = np.asarray(X_classification_test, dtype=np.float64)
# Получаем предсказания модели
predictions_classifier = mlp_classifier.predict(X_test_classifier)

In [37]:
from sklearn.metrics import accuracy_score
y_test_classifier = np.asarray(y_classification_test, dtype=np.float64)
accuracy = accuracy_score(y_test_classifier, predictions_classifier)
print("Accuracy:", accuracy)

ValueError: Classification metrics can't handle a mix of binary and unknown targets